drop table if exists hurricane cascade;

CREATE TABLE hurricane (
	pkey TEXT, 
	keynumber TEXT, 
	folioid TEXT, 
	eventkeynumber TEXT, 
	event TEXT, 
	eventtype TEXT, 
	eventdate DATE, 
	reporttype TEXT, 
	repairstatus TEXT, 
	description TEXT, 
	repaired TEXT, 
	repairstatusdate DATE, 
	comments TEXT, 
	buildingno TEXT, 
	buildingkey TEXT, 
	totaldamagepct TEXT, 
	damagecategory TEXT, 
	structurevalue TEXT, 
	damageamount TEXT, 
	adjustmentamount TEXT, 
	adjustmenttype TEXT, 
	marketvalue TEXT, 
	milestone TEXT, 
	buildingdamage TEXT, 
	subareadamage TEXT, 
	xfeaturedamage TEXT, 
	iscalamity TEXT, 
	maintdate TIMESTAMP, 
	maintuser TEXT, 
	createddate TIMESTAMP, 
	createduser TEXT, 
	roofdamage TEXT, 
	extwalldamage TEXT, 
	intwalldamage TEXT, 
	floordamage TEXT, 
	foundationdamage TEXT, 
	plumbingdamage TEXT, 
	electricdamage TEXT, 
	acdamage TEXT, 
	poweroff TEXT, 
	uninhabitable TEXT, 
	waterpresent TEXT, 
	confidential TEXT, 
	streetnumber TEXT, 
	streetname TEXT, 
	unit TEXT, 
	city TEXT, 
	zip TEXT, 
	searchaddress TEXT, 
	latitude TEXT, 
	longitude TEXT, 
	municode TEXT, 
	dorcode TEXT, 
	dordescription TEXT, 
	dortype TEXT
);

\copy hurricane from 'data/hurricane.csv' csv header;
